spring:
   application:
      name: kafkaEmail
   mail:
      host: smtp.gmail.com
      port: 587
      username: your-email@gmail.com
      password: your-app-password
      properties:
         mail:
            smtp:
               auth: true
               starttls:
                  enable: true
               ssl:
                  trust: smtp.gmail.com
      
server:
   port: 8080

kafka:
   host: localhost
   port: 29092
   bootstrapAddress: ${kafka.host}:${kafka.port}